name: Go CI

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Get dependencies
      run: go get -v -t -d ./...
    - run: |
        go test -v -coverprofile cover.out ./...
        go tool cover -func cover.out
